using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace configuratore
{
    public class loca
    {

        public struct strQ
        {
            public indice textGBox;
            public indice[] textLabels;
            public indice[] RadioLabel;
        }



        public const int ITALIANO = 0;
        public const int INGLESE = 1;
        static int Linguaggio;

        public const int NUMERO_LINGUE = 2;


        static public void initLinguaggioIta()
        {
            Linguaggio = ITALIANO;
        }

        static public int getLingua()
        {
            return Linguaggio;
        }

        static public void setLinguaggio(int l)
        {
            Linguaggio = l;
        }

        // <INIZIO STRINGHE>
		public enum indice
			{
				/*   0 */ GB0_FUNZIONAMENTO_CASSETTA,
				/*   1 */ FUNZIONAMENTO,
				/*   2 */ VAV,
				/*   3 */ STANDARD,
				/*   4 */ GB1_FUNZIONAMENTO_CASSETTA,
				/*   5 */ ZONA_MORTA_RISC_HDZ,
				/*   6 */ BANDA_REGOLAZIONE_RISC_HB,
				/*   7 */ KI_REGOLAZIONE_RISCALDAMENTO,
				/*   8 */ PERIODO_MODULAZIONE_PWM,
				/*   9 */ MINIMO_DC_RESISTENZA,
				/*  10 */ MASSIMO_DC_RESISTENZA,
				/*  11 */ POTENZA_NOMINALE_RESISTENZA,
				/*  12 */ PRESENZA_RESISTENZA,
				/*  13 */ GB2_MAX_POT_RES,
				/*  14 */ LIM_POT_MAX,
				/*  15 */ TEMP_ARIA_PRIM,
				/*  16 */ ON,
				/*  17 */ OFF,
				/*  18 */ GB3_IMP_REG_AMP,
				/*  19 */ SETPOINT_DEFAULT,
				/*  20 */ DEV_MAX_SETPOINT,
				/*  21 */ INCR_ZONA_MORTA_DZI,
				/*  22 */ GB4_REGOLAZIONTEMP_INTERNA,
				/*  23 */ PRIMA_SOGLIA,
				/*  24 */ IST_PRIMA_SOGLIA,
				/*  25 */ SEC_SOGLIA,
				/*  26 */ IST_SECONDA_SOGLIA,
				/*  27 */ GB5_GEOMETRIA_CASSETTA,
				/*  28 */ DIFFUSIONE,
				/*  29 */ DAL_BASSO,
				/*  30 */ IN_LINEA,
				/*  31 */ GB6_LIMITE_TEMP_MANDATA,
				/*  32 */ SETPOINT_LIM_MAX_HLSP,
				/*  33 */ BANDA_REGOLAZIONE_LB,
				/*  34 */ GB7_REGOLAZIONESERRANDA,
				/*  35 */ ZONA_MORTA_SERRANDA_DDZ,
				/*  36 */ BANDA_DI_REG_SERRANDA_DB,
				/*  37 */ KI_REGOLAZIONE_SERRANDA,
				/*  38 */ APERT_SERRANDA_MIN,
				/*  39 */ APERT_SERRANDA_MAX,
				/*  40 */ PRESENZA_SERRANDA,
				/*  41 */ GB8_GEST_MOD_ECONOMY,
				/*  42 */ TIPO_ECONOMY,
				/*  43 */ T2_AUMENTO_ZM_E_BANDA,
				/*  44 */ T3_OFF,
				/*  45 */ TASTO_ECONOMY,
				/*  46 */ GB9_GESTIONE_PORTATA,
				/*  47 */ ABILITA_VIS_PORT_IST,
				/*  48 */ PORT_MIN,
				/*  49 */ PORT_MAX,
				/*  50 */ PORT_MIN_SICUREZZA,
				/*  51 */ SEZIONE,
				/*  52 */ OFFSET_MIS_PORTATA,
				/*  53 */ TEMP_LETT_SENSORE,
				/*  54 */ K_APERT_SERR_0_10,
				/*  55 */ K_APERT_SERR_10_20,
				/*  56 */ K_APERT_SERR_20_30,
				/*  57 */ K_APERT_SERR_30_40,
				/*  58 */ K_APERT_SERR_40_50,
				/*  59 */ K_APERT_SERR_50_60,
				/*  60 */ K_APERT_SERR_60_70,
				/*  61 */ K_APERT_SERR_70_80,
				/*  62 */ K_APERT_SERR_80_90,
				/*  63 */ K_APERT_SERR_90_100,
				/*  64 */ MSG_WORNING,
				/*  65 */ MSG_FILE_EXIEST,
				/*  66 */ MENU_FILE,
				/*  67 */ MENU__APRI,
				/*  68 */ MENU_SALVA,
				/*  69 */ MENU_SALVA_COME,
				/*  70 */ MENU_NUOVO,
				/*  71 */ MENU_ESCI,
				/*  72 */ MENU_COM,
				/*  73 */ MENU_CONNETTI,
				/*  74 */ MWNU_DISCONNETTI,
				/*  75 */ MENU_DEVICE,
				/*  76 */ MENU_LINGUA,
				/*  77 */ MENU_ITALIANO,
				/*  78 */ MENU_INGLESE,
				/*  79 */ MENU_CASSETTE,
				/*  80 */ MENU_FANCOIL,
				/*  81 */ LBL_CONNECTED,
				/*  82 */ LBL_UNCONNECTED,
				/*  83 */ MSG_FINAPERTA,
				/*  84 */ VUOTO,
				/*  85 */ GB10_INGRESSI,      
				/*  86 */ INPUT_D1,           
				/*  87 */ INPUT_D2,           
				/*  88 */ INPUT_D3,           
				/*  89 */ INPUT_NTC1,         
				/*  90 */ INPUT_NTC2,         
				/*  91 */ LOGICA_D1,          
				/*  92 */ LOGICA_D2,          
				/*  93 */ LOGICA_D3,          
				/*  94 */ LOGICA_NTC2,  
				/*  95 */ LOGICA_FUNZIONAMENTO_SERRANDA,
				/*  96 */ DIRETTA,
				/*  97 */ INVERSA,
				/*  98 */ NORM_AP,
				/*  99 */ NORM_CH,
				/* 100 */ TERM_RESISTENZA,
				/* 101 */ ONOFF_DAREMOTO,
				/* 102 */ STR_ECONOMY,
				/* 103 */ SONDA_INT,
				/* 104 */ SONDA_MAND,
				/* 105 */ SONDA_AMB,
                /* 106 */ GB11_INTENSITALED,
                /* 107 */ STR_SET_INTENSITALED,
                /* 108 */ PORTATA_LS,
				/* 109 */ STR_INT_MANDATA,
				/* 110 */ STR_CARICA_PARAMETRI,
                /* 111 */ TENSIONE_SERRANDA_MINIMA,
				/* 112 */ TENSIONE_SERRANDA_MASSIMA,
                /* 113 */ STR_CONNECTING,
				/* 114 */ IMPOSTAZIONE_CASSETTA,
				/* 115 */ TIPO_CASSETTA,
            // ----------------------------------------------------------
/* 116 */ FC_TAB_0,
/* 117 */ FC_GB_0_STR_INGRESSI,
/* 118 */ FC_LBL_0_00,
/* 119 */ FC_LBL_0_01,
/* 120 */ FC_LBL_0_02,
/* 121 */ FC_LBL_0_03,
/* 122 */ FC_LBL_0_04,
/* 123 */ FC_LBL_0_05,
/* 124 */ FC_LBL_0_06,
/* 125 */ FC_LBL_0_07,
/* 126 */ FC_LBL_0_08,
/* 127 */ FC_LBL_0_09,
/* 128 */ FC_LBL_0_10,
/* 129 */ FC_LBL_0_11,
/* 130 */ FC_LBL_0_12,
/* 131 */ FC_LBL_0_13,
/* 132 */ FC_LBL_0_14,
/* 133 */ FC_LBL_0_15,
/* 134 */ FC_LBL_0_16,
/* 135 */ FC_LBL_0_17,
/* 136 */ FC_LBL_0_18,
/* 137 */ FC_CB_0_00_0,
/* 138 */ FC_CB_0_00_1,
/* 139 */ FC_CB_0_00_2,
/* 140 */ FC_CB_0_00_3,
/* 141 */ FC_CB_0_01_0,
/* 142 */ FC_CB_0_01_1,
/* 143 */ FC_CB_0_02_0,
/* 144 */ FC_CB_0_02_1,
/* 145 */ FC_GB_1_STR_TRITARDO,
/* 146 */ FC_LBL_1_00,
/* 147 */ FC_LBL_1_01,
/* 148 */ FC_LBL_1_02,
/* 149 */ FC_LBL_1_03,
/* 150 */ FC_LBL_1_04,
/* 151 */ FC_LBL_1_05,
/* 152 */ FC_GB_2_STR_USCITE,
/* 153 */ FC_LBL_2_00,
/* 154 */ FC_LBL_2_01,
/* 155 */ FC_LBL_2_02,
/* 156 */ FC_LBL_2_03,
/* 157 */ FC_CMB_2_00,
/* 158 */ FC_CMB_2_01,
/* 159 */ FC_CMB_2_02,
/* 160 */ FC_CMB_2_03,
/* 161 */ FC_CMB_2_04,
/* 162 */ FC_CMB_2_05,
/* 163 */ FC_CMB_2_06,
/* 164 */ FC_CMB_2_07,
/* 165 */ FC_CMB_2_08,
/* 166 */ FC_CMB_2_09,
/* 167 */ FC_CMB_2_10,
/* 168 */ FC_CMB_2_11,
/* 169 */ FC_CMB_2_12,
/* 170 */ FC_CMB_2_13,
/* 171 */ FC_CMB_2_14,
/* 172 */ FC_CMB_2_15,
/* 173 */ FC_RB_2_00_0,
/* 174 */ FC_RB_2_00_1,
/* 175 */ FC_RB_2_00_2,
/* 176 */ FC_RB_2_01_0,
/* 177 */ FC_RB_2_01_1,
/* 178 */ FC_RB_2_02_0,
/* 179 */ FC_RB_2_02_1,
/* 180 */ FC_GB_3_SEGN_FILTRO_SPORCO,
/* 181 */ FC_LBL_3_00,
/* 182 */ FC_LBL_3_01,
/* 183 */ FC_LBL_3_02,
/* 184 */ FC_BTN_3_00,
/* 185 */ FC_TAB_1,
/* 186 */ FC_GB_4_REGOLAZIONE_RISC,
/* 187 */ FC_LBL_4_00,
/* 188 */ FC_LBL_4_01,
/* 189 */ FC_LBL_4_02,
/* 190 */ FC_LBL_4_03,
/* 191 */ FC_LBL_4_04,
/* 192 */ FC_LBL_4_05,
/* 193 */ FC_LBL_4_06,
/* 194 */ FC_GB_5_REGOLAZIONE_FREDDO,
/* 195 */ FC_LBL_5_00,
/* 196 */ FC_LBL_5_01,
/* 197 */ FC_LBL_5_02,
/* 198 */ FC_LBL_5_03,
/* 199 */ FC_LBL_5_04,
/* 200 */ FC_LBL_5_05,
/* 201 */ FC_LBL_5_06,
/* 202 */ FC_LBL_5_07,
/* 203 */ FC_LBL_5_08,
/* 204 */ FC_GB_6_REGOLAZIONE_VENTILATORE,
/* 205 */ FC_LBL_6_00,
/* 206 */ FC_LBL_6_01,
/* 207 */ FC_LBL_6_02,
/* 208 */ FC_LBL_6_03,
/* 209 */ FC_LBL_6_04,
/* 210 */ FC_LBL_6_05,
/* 211 */ FC_LBL_6_06,
/* 212 */ FC_LBL_6_07,
/* 213 */ FC_LBL_6_08,
/* 214 */ FC_LBL_6_09,
/* 215 */ FC_GB_7_REGOLAZIONE_SERRANDA_FA,
/* 216 */ FC_LBL_7_00,
/* 217 */ FC_LBL_7_01,
/* 218 */ FC_LBL_7_02,
/* 219 */ FC_LBL_7_03,
/* 220 */ FC_LBL_7_04,
/* 221 */ FC_LBL_7_05,
/* 222 */ FC_LBL_7_06,
/* 223 */ FC_LBL_7_07,
/* 224 */ FC_LBL_7_08,
/* 225 */ FC_LBL_7_09,
/* 226 */ FC_LBL_7_10,
/* 227 */ FC_LBL_7_11,
/* 228 */ FC_LBL_7_12,
/* 229 */ FC_CB_7_00,
/* 230 */ FC_CB_7_01,
/* 231 */ FC_CB_7_02,
/* 232 */ FC_TAB_2,
/* 233 */ FC_GB_8_IMPOSTAZIONE_SONDA,
/* 234 */ FC_LBL_8_00,
/* 235 */ FC_LBL_8_01,
/* 236 */ FC_LBL_8_02,
/* 237 */ FC_CB_8_00_00,
/* 238 */ FC_CB_8_00_01,
/* 239 */ FC_CB_8_00_02,
/* 240 */ FC_CB_8_00_03,
/* 241 */ FC_CB_8_00_04,
/* 242 */ FC_CB_8_00_05,
/* 243 */ FC_CB_8_01_00,
/* 244 */ FC_CB_8_01_01,
/* 245 */ FC_CB_8_01_02,
/* 246 */ FC_GB_9_SENSORE_PRESSIONE,
/* 247 */ FC_LBL_9_00,
/* 248 */ FC_LBL_9_01,
/* 249 */ FC_LBL_9_02,
/* 250 */ FC_LBL_9_03,
/* 251 */ FC_LBL_9_04,
/* 252 */ FC_LBL_9_05,
/* 253 */ FC_LBL_9_06,
/* 254 */ FC_GB_10_TEMP_INTERNA,
/* 255 */ FC_LBL_10_00,
/* 256 */ FC_LBL_10_01,
/* 257 */ FC_GB_11_TEMP_MADATA,
/* 258 */ FC_LBL_11_00,
/* 259 */ FC_LBL_11_01,
/* 260 */ FC_LBL_11_02,
/* 261 */ FC_LBL_11_03,
/* 262 */ FC_GB_12_RAMPA_VENTIL,
/* 263 */ FC_LBL_12_00,
/* 264 */ FC_LBL_12_01,
/* 265 */ FC_TAB_3,
/* 266 */ FC_GB_13_IMPOSTAZIONI_RETE,
/* 267 */ FC_LBL_13_00,
/* 268 */ FC_LBL_13_01,
/* 269 */ FC_LBL_13_02,
/* 270 */ FC_LBL_13_03,
/* 271 */ FC_LBL_13_04,
/* 272 */ FC_RB_LBL_13_00,
/* 273 */ FC_RB_LBL_13_01,
/* 274 */ FC_CB_13_00_2400,
/* 275 */ FC_CB_13_00_4800,
/* 276 */ FC_CB_13_00_9600,
/* 277 */ FC_CB_13_00_19200,
/* 278 */ FC_CB_13_00_38400,
/* 279 */ FC_CB_13_00_57600,
/* 280 */ FC_CB_13_00_115200,
/* 281 */ FC_CB_13_01_00_NESSUNA,
/* 282 */ FC_CB_13_01_00_PARI,
/* 283 */ FC_CB_13_01_00_DISPARI,
/* 284 */ FC_CB_13_02_BITSTOP_1,
/* 285 */ FC_BC_13_02_BITSTOP_2,
/* 286 */ FC_GB15_RegolazioneChangeOver,
/* 287 */ FC_LBL_15_00,
/* 288 */ FC_LBL_15_01,
/* 289 */ FC_LBL_15_02,
/* 290 */ FC_CB_15_00,
/* 291 */ FC_CB_15_01,
/* 292 */ FC_GB17_ECONOMYMODE,
/* 293 */ FC_LBL_17_00_TED1,
/* 294 */ FC_LBL_17_01_TED2,
/* 295 */ FC_LBL_17_02_TED3,
/* 296 */ FC_LBL_17_03_PRIORITA,
/* 297 */ FC_LBL_17_04_HDZI1,
/* 298 */ FC_LBL_17_05_CDZI1,
/* 299 */ FC_LBL_17_06_HDZI2,
/* 300 */ FC_LBL_17_07_CDZI2,
/* 301 */ FC_CB_17_00_TIPO_ECONOMY_00,
/* 302 */ FC_CB_17_00_TIPO_ECONOMY_01,
/* 303 */ FC_CB_17_00_TIPO_ECONOMY_02,
/* 304 */ FC_CB_17_00_TIPO_ECONOMY_03,
/* 305 */ FC_CB_17_01_PRIOROTA_00,
/* 306 */ FC_CB_17_01_PRIOROTA_01,
/* 307 */ FC_CB_17_01_PRIOROTA_02,
/* 308 */ FC_CB_17_01_PRIOROTA_03,
/* 309 */ FC_CB_17_01_PRIOROTA_04,
/* 310 */ FC_CB_17_01_PRIOROTA_05,
/* 311 */ FC_GB16_ExtPressSens,
/* 312 */ FC_LBL_16_00_VoltageRange,
/* 313 */ FC_LBL_16_01_PressRange,
/* 314 */ FC_LBL_16_02_AlarmTreshold,
/* 315 */ FC_CB_16_00_RANGETENSIONE_00,
/* 316 */ FC_CB_16_00_RANGETENSIONE_01,
/* 317 */ FC_CB_16_01_RANGEPRESSIONE_00,
/* 318 */ FC_CB_16_01_RANGEPRESSIONE_01,
/* 319 */ FC_CB_16_01_RANGEPRESSIONE_02,
/* 320 */ FC_CB_16_01_RANGEPRESSIONE_03,
/* 321 */ FC_CB_16_01_RANGEPRESSIONE_04,
/* 322 */ FC_CB_16_01_RANGEPRESSIONE_05,





// -------------------------------------- T1
/* 327 */ T1_GB_0,
/* 328 */ T1_LBL_0_00,
/* 329 */ T1_LBL_0_01,
/* 330 */ T1_LBL_0_02,
/* 331 */ T1_LBL_0_03,
/* 332 */ T1_LBL_0_04,
/* 333 */ T1_GB_1,
/* 334 */ T1_LBL_1_00,



// ------------------------------ T2
/* 335 */ T2_GB_0,
/* 336 */ T2_LBL_0_00,
/* 337 */ T2_LBL_0_01,
/* 338 */ T2_LBL_0_02,
/* 339 */ T2_LBL_0_03,
/* 340 */ T2_LBL_0_04,
/* 341 */ T2_LBL_0_05,
/* 342 */ T2_CB_0_00,
/* 343 */ T2_CB_0_01,
/* 344 */ T2_CB_0_02,
/* 345 */ T2_CB_0_03,
/* 346 */ T2_CB_0_04,
/* 347 */ T2_CB_0_05,
/* 348 */ T2_LBL_1_01,



// ------------------------------ MASTER NETWORK

/* 349 */ MNET_H_DISPOSITIVO,
/* 350 */ MNET_H_INDIRIZZO,
/* 351 */ MNET_H_MATRICOLA,
/* 352 */ MNET_H_STATO,
/* 353 */ MNET_B_RESET,
/* 354 */ MNET_B_UPDATE,
/* 355 */ MNET_B_FIX,
/* 356 */ MNET_B_ESCI,
/* 357 */ MNET_MSG_ERROR_1,
/* 358 */ MNET_MSG_ERROR,
/* 359 */ MNET_MSG_ERROR_2,
/* 360 */ MNET_MSG_RESTART,
/* 361 */ MNET_MSG_SAVED,
/* 362 */ MNET_MSG_DNOTSAVED,
/* 363 */ MNET_MSG_INFO,
/* 364 */ MNET_MSG_WARNING,
/* 365 */ MNET_MSG_NO_PRINCIPALE,
/* 366 */ MNET_H_SW_RELEASE,
/* 367 */ MNET_MSG_RESATART,


// ---------- STARTUP
/* 368 */ STARTUP_DISCONNSSIONE_INCORSO,
/* 369 */ STARTUP_DISCONNESSO,
/* 370 */ STARTUP_CONNECTION_ERROR,



            /* 282 */
            NUM_OF_STRING,

				// GENERICO 
                MSG_ERRORE,
				ERR_NON_COMPATIBILE,
				INVALID_SERIAL_NUMBER,
				TOTALE

        }
		static string[,] localizzazioni = new string[(int)indice.NUM_OF_STRING, NUMERO_LINGUE] {
		/*   0 GB1_FUNZIONAMENTO_CASSETTA          */ {"Funzionamento cassetta","ATU operating mode"},
		/*   1 FUNZIONAMENTO                       */ {"Funzionamento","Operating mode"},
		/*   2 VAV                                 */ {"VAV","VAV"},
		/*   3 STANDARD                            */ {"STANDARD","STANDARD"},
		/*   4 GB2_FUNZIONAMENTO_CASSETTA          */ {"Regolazione riscaldamento","Heating setting"},
		/*   5 ZONA_MORTA_RISC_HDZ                 */ {"Zona morta riscaldamento H.D.Z. [C°]","Heating dead Zone H.D.Z. [C°]"},
		/*   6 BANDA_REGOLAZIONE_RISC_HB           */ {"Banda di regolazione riscaldamento H.B. [C°]","Heating band H.B. [C°]"},
		/*   7 KI_REGOLAZIONE_RISCALDAMENTO        */ {"KI regolazione riscaldamento [%]","Heating regulation [%]"},
		/*   8 PERIODO_MODULAZIONE_PWM             */ {"Periodo modulazione PWM [s]","PWM modulation period [s]"},
		/*   9 MINIMO_DC_RESISTENZA                */ {"Minimo duty cycle resistenza el. [%]","Minimum duty cycle [%]"},
		/*  10 MASSIMO_DC_RESISTENZA               */ {"Massimo duty cycle resistenza el. [%]","Maximum duty cycle [%]"},
		/*  11 POTENZA_NOMINALE_RESISTENZA         */ {"Potenza nominale resistenza  [W]","El. heater nominal power [W]"},
		/*  12 PRESENZA_RESISTENZA                 */ {"Presenza resistenza elettrica","El. heater presence"},
		/*  13 GB3_MAX_POT_RES                     */ {"Max potenza resistenza in funzione della portata","Max el. heater power as a function of flow rate"},
		/*  14 LIM_POT_MAX                         */ {"Limitazione potenza massima res.","Max el. power limitation"},
		/*  15 TEMP_ARIA_PRIM                      */ {"Temperatura aria primaria [C°]","Primary air temperature [C°]"},
		/*  16 ON                                  */ {"ON","ON"},
		/*  17 OFF                                 */ {"OFF","OFF"},
		/*  18 GB4_IMP_REG_AMP                     */ {"Impostazione regolazione ambiente","Room temperature setting"},
		/*  19 SETPOINT_DEFAULT                    */ {"Setpoint default [C°]","Default temperatrure setpoint [C°]"},
		/*  20 DEV_MAX_SETPOINT                    */ {"Deviazione maxsetpoint default [C°] ±","Max. default setpoint deviation [C°] ±"},
		/*  21 INCR_ZONA_MORTA_DZI                 */ {"Incremento zona morta risc./raff. in \neconomy mode D.Z.I.","Heating/cooling dead zone increase in\neconomy mode D.Z.I. [C°]"},
		/*  22 GB5_REGOLAZIONTEMP_INTERNA          */ {"Regolazione temperatura interna","Internal temperature management"},
		/*  23 PRIMA_SOGLIA                        */ {"1ª soglia OFF resistenza [C°]","1ª el. heater OFF threshold [C°]"},
		/*  24 IST_PRIMA_SOGLIA                    */ {"Isteresi prima soglia [C°]","1ª threshold hysteresis[C°]"},
		/*  25 SEC_SOGLIA                          */ {"2ª soglia OFF resistenza [C°]","2ª el. heater OFF threshold [C°]"},
		/*  26 IST_SECONDA_SOGLIA                  */ {"Isteresi seconda soglia [C°]","2ª threshold hysteresis[C°]"},
		/*  27 GB6_GEOMETRIA_CASSETTA              */ {"Geometria cassetta","ATU geometry"},
		/*  28 DIFFUSIONE                          */ {"Diffusione","Air diffusion"},
		/*  29 DAL_BASSO                           */ {"DAL BASSO","FROM BELOW"},
		/*  30 IN_LINEA                            */ {"IN LINEA","ON LINE"},
		/*  31 GB7_LIMITE_TEMP_MANDATA             */ {"Limiti temperatura mandata","Supply air temperature limits"},
		/*  32 SETPOINT_LIM_MAX_HLSP               */ {"Setpoint limite massimo H.L.S.P. [C°]","High limit setpoint H.L.S.P. [C°]"},
		/*  33 BANDA_REGOLAZIONE_LB                */ {"Banda regolazione limiti L.B. [C°]","Limit regulation band L.B. [C°]"},
		/*  34 GB8_REGOLAZIONESERRANDA             */ {"Recolazione serranda","Damper settings"},
		/*  35 ZONA_MORTA_SERRANDA_DDZ             */ {"Zona morta serranda D.D.Z.  [C°]","Damper dead zone D.D.Z.  [C°]"},
		/*  36 BANDA_DI_REG_SERRANDA_DB            */ {"Banda di regolazione serranda D.B.  [C°]","Damper regulation band  [C°]"},
		/*  37 KI_REGOLAZIONE_SERRANDA             */ {"KI regolazione serranda [%]","KI damper regulation [%]"},
		/*  38 APERT_SERRANDA_MIN                  */ {"Apertura serranda minima [%]","Minumum damper oprning [%]"},
		/*  39 APERT_SERRANDA_MAX                  */ {"Apertura serranda massima [%]","Maximum damper opening [%]"},
		/*  40 PRESENZA_SERRANDA                   */ {"Presenza serranda","Damper presence"},
		/*  41 GB9_GEST_MOD_ECONOMY                */ {"Gestione modalità economy","Economy mode managment"},
		/*  42 TIPO_ECONOMY                        */ {"Tipo economy","Economy mode"},
		/*  43 T2_AUMENTO_ZM_E_BANDA               */ {"2) aumento zm e banda","2) dz and band increases"},
		/*  44 T3_OFF                              */ {"3) OFF","3) OFF"},
		/*  45 TASTO_ECONOMY                       */ {"Tasto \"economy\" - riduzione % portata\nminima / apertura serranda","\"Economy\" key - % reduction of min\nflow rate / min. Damper opening"},
		/*  46 GB10_GESTIONE_PORTATA               */ {"Gestione portata","Flow rate management"},
		/*  47 ABILITA_VIS_PORT_IST                */ {"Abilita visualizzazione portata istantanea","Enable instand flow r. visualization"},
		/*  48 PORT_MIN                            */ {"Portata min [m³/h]","Min. flow rate"},
		/*  49 PORT_MAX                            */ {"Portata max  [m³/h]","Max. flow rate"},
		/*  50 PORT_MIN_SICUREZZA                  */ {"Portata min  sicurezza [m³/h]","Min.. Safety flow rate  [m³/s]"},
		/*  51 SEZIONE                             */ {"Sezione per misurazione di portata [cm²]","Section for flow r. measurement [cm²]"},
		/*  52 OFFSET_MIS_PORTATA                  */ {"Offset misuraz. di portata [±cm²]","Section offset [±cm²]"},
		/*  53 TEMP_LETT_SENSORE                   */ {"Tempo lettura sensore [s]","Sensor reading time [s]"},
		/*  54 K_APERT_SERR_0_10                   */ {"K apertura serranda [0% - 10%]","Damper opening K [0% - 10%]"},
		/*  55 K_APERT_SERR_10_20                  */ {"K apertura serranda [10% - 10%]","Damper opening K [10% - 10%]"},
		/*  56 K_APERT_SERR_20_30                  */ {"K apertura serranda [20% - 10%]","Damper opening K [20% - 10%]"},
		/*  57 K_APERT_SERR_30_40                  */ {"K apertura serranda [30% - 40%]","Damper opening K [30% - 40%]"},
		/*  58 K_APERT_SERR_40_50                  */ {"K apertura serranda [40% - 50%]","Damper opening K [40% - 50%]"},
		/*  59 K_APERT_SERR_50_60                  */ {"K apertura serranda [50% - 60%]","Damper opening K [50% - 60%]"},
		/*  60 K_APERT_SERR_60_70                  */ {"K apertura serranda [60% - 70%]","Damper opening K [60% - 70%]"},
		/*  61 K_APERT_SERR_70_80                  */ {"K apertura serranda [70% - 80%]","Damper opening K [[70% - 80%]"},
		/*  62 K_APERT_SERR_80_90                  */ {"K apertura serranda [80% - 90%]","Damper opening K [80% - 90%]"},
		/*  63 K_APERT_SERR_90_100                 */ {"K apertura serranda [90% - 100%]","Damper opening K [90% - 100%]"},
		/*  64 MSG_WORNING                         */ {"Attenzione!!","Worning!!"},
		/*  65 MSG_FILE_EXIEST                     */ {"Il file {0} esiste. Sovrascriverlo ?","File {0} olaready exists. Overwrite ?"},
		/*  66 MENU_FILE                           */ {"File","File"},
		/*  67 MENU__APRI                          */ {"Apri","Open"},
		/*  68 MENU_SALVA                          */ {"Salva","Save"},
		/*  69 MENU_SALVA_COME                     */ {"Salva come ...","Save as ..."},
		/*  70 MENU_NUOVO                          */ {"Nuovo","New"},
		/*  71 MENU_ESCI                           */ {"Esci","Exit"},
		/*  72 MENU_COM                            */ {"COM","COM"},
		/*  73 MENU_CONNETTI                       */ {"Connetti","Connect"},
		/*  74 MWNU_DISCONNETTI                    */ {"Disconnetti","Disconnect"},
		/*  75 MENU_DEVICE                         */ {"Dispositivo","Device"},
		/*  76 MENU_LINGUA                         */ {"Lingua","Language"},
		/*  77 MENU_ITALIANO                       */ {"Italiano","Italiano"},
		/*  78 MENU_INGLESE                        */ {"English","English"},
		/*  79 MENU_CASSETTE                       */ {"CASSETTE","CASSETTE"},
		/*  80 MENU_FANCOIL                        */ {"FANCOIL","FANCOIL"},
		/*  81 LBL_CONNECTED                       */ {"CONNESSO","CONNECTED"},
		/*  82 LBL_UNCONNECTED                     */ {"NON CONNESSO","UNCONNECTED"},
		/*  83 MSG_FINAPERTA                       */ {"E' già aperta una finestra di configurazione. Procedere in ogni caso ?","Setting window is already open. Proceed ?"},
        /*  84 VUOTO                               */ {"",""},
		/*  85 GB10_INGRESSI                       */ {"Ingressi","Inputs"},
		/*  86 INPUT_D1                            */ {"Ingresso digitale D1","D1 digital input"},
		/*  87 INPUT_D2                            */ {"Ingresso digitale D2","D2 digital input"},
		/*  88 INPUT_D3                            */ {"Ingresso digitale D3","D2 digital input"},
		/*  89 INPUT_NTC1                          */ {"Ingresso analogico NTC1","NTC1 analog input"},
		/*  90 INPUT_NTC2                          */ {"Ingresso analogico NTC2","NTC1 analog input"},
		/*  91 LOGICA_D1                           */ {"Logica D1","D1 logic"},
		/*  92 LOGICA_D2                           */ {"Logica D2","D2 logic"},
		/*  93 LOGICA_D3                           */ {"Logica D3","D3 logic"},
		/*  94 LOGICA_NTC2                         */ {"Logica NTC2","NTC2 logic"},
		/*  95 LOGICA_FUNZIONAMENTO_SERRANDA       */ {"Logica funzionamento serranda","Damper operation logica"},
		/*  96 DIRETTA                             */ {"DIRETTA","DIRECT"},
		/*  97 INVERSA                             */ {"INVERSA","INVERSE"},
		/*  98 MORM_AP                             */ {"n.a","n.o" },
		/*  98 MORM_CH                             */ {"n.c","n.c" },
		/* 100 TERM_RESISTENZA                     */ { "TERMOSTATO RESISTENZA","SAFETY THERMOSTAT" },
		/* 101 ONOFF_DAREMOTO                      */ { "ON OFF DA REMOTO", "REMOTE ON OFF" },
		/* 102 STR_ECONOMY                         */ { "ECONOMY", "ECONOMY" },
		/* 103 SONDA_INT                           */ { "SONDA INTERNA", "INTERNAL PROBE" },
		/* 104 SONDA_MAND                          */ { "SONDA MANDATA", "FLOW PROBE" },
		/* 105 SONDA_AMB                           */ { "SONDA AMBIENTE", "ENVIRONMENT PROBE" },
		/* 106 GB11_INTENSITALED                   */ { "Intensita LED","LED intensity" },
		/* 107 STR_SET_INTENSITALED                */ { "Impostazione intensità LED","Set LED intensity" },
		/* 110 PORTATA_LS                          */ { "[l/s]","[l/s]" },
		/* 109 STR_INT_MANDATA                     */ { "SONDA INTERNA + MANDATA","INTERNAL + FLOW PROBE" },
		/* 110 STR_CARICA_PARAMETRI                */ { "Caricamento parametri. Attendere.","Loading parameters. Please wait." },
		/* 111 TENSIONE_SERRANDA_MINIMA            */ { "Tensione serranda allo 0% [V]","Damper voltage at 0% [V]" },
		/* 112 TENSIONE_SERRANDA_MASSIMA           */ { "Tensione serranda al 100% [V]","Damper voltage at 100% [V]" },
		/* 113 STR_CONNECTING                      */ { "IN CONNESSIONE. ATTENDERE ....","CONNECTING. PLEASE WAIT ...." },
		/* 114 IMPOSTAZIONE_CASSETTA               */ { "Impostazione CASSETTE","CASSETTE setting"},
		/* 115 TIPO_CASSETTA                   */ { "Tipo CASSETTE","CASSETTE type"},
			// -----------------------------------------------------------------------  FANCOIL
/* 116 FC_TAB_0                            */ { "Ingressi – Uscite","Inputs – Outputs"},
/* 117 FC_GB_0_STR_INGRESSI                */ { "Ingressi","Input"},
/* 118 FC_LBL_0_00                         */ { "DI1","DI1"},
/* 119 FC_LBL_0_01                         */ { "DI2","DI2"},
/* 120 FC_LBL_0_02                         */ { "DI3","DI3"},
/* 121 FC_LBL_0_03                         */ { "DI4","DI4"},
/* 122 FC_LBL_0_04                         */ { "DI5","DI5"},
/* 123 FC_LBL_0_05                         */ { "NTC1","NTC1"},
/* 124 FC_LBL_0_06                         */ { "NTC2","NTC2"},
/* 125 FC_LBL_0_07                         */ { "AI1","AI1"},
/* 126 FC_LBL_0_08                         */ { "AI2","AI2"},
/* 127 FC_LBL_0_09                         */ { "logica DI1: contatto presenza","logic DI1: presence contact"},
/* 128 FC_LBL_0_10                         */ { "logica DI2: contatto porta terrazza","logic DI2: balcony door contact"},
/* 129 FC_LBL_0_11                         */ { "logica DI3: tessera magnetica","logic DI3: keycard holder"},
/* 130 FC_LBL_0_12                         */ { "logica DI5: termostato sicurezza","logic DI5: electric heter safety switch"},
/* 131 FC_LBL_0_13                         */ { "contatto porta terrazza","balcony contact"},
/* 132 FC_LBL_0_14                         */ { "tessera magnetica","keycard holder"},
/* 133 FC_LBL_0_15                         */ { "feedback ventilatore","fan feedback"},
/* 134 FC_LBL_0_16                         */ { "termostato sicurezza resistenza","electric heater safety switch"},
/* 135 FC_LBL_0_17                         */ { "temperatura interna","internal temperature"},
/* 136 FC_LBL_0_18                         */ { "Feedback serranda","Feedback serranda"},
/* 137 FC_CB_0_00_0                        */ { "contatto presenza","presence contact"},
/* 138 FC_CB_0_00_1                        */ { "pressostato filtro","filter pressure switch"},
/* 139 FC_CB_0_00_2                        */ { "allarme fuoco/gen.","fire/general alarm"},
/* 140 FC_CB_0_00_3                        */ { "ON-OFF","ON-OFF"},
/* 141 FC_CB_0_01_0                        */ { "Ripresa",""},
/* 142 FC_CB_0_01_1                        */ { "Mandata",""},
/* 143 FC_CB_0_02_0                        */ { "CO₂","CO₂"},
/* 144 FC_CB_0_02_1                        */ { "VOC","VOC"},
/* 145 FC_GB_1_STR_TRITARDO                */ { "Tempi di ritardo","Inputs delay time"},
/* 146 FC_LBL_1_00                         */ { "Attivazione DI1 [s]","DI1 activation [s]"},
/* 147 FC_LBL_1_01                         */ { "Disattivazione DI1 [s]","DI1 deactivation [s]"},
/* 148 FC_LBL_1_02                         */ { "Attivazione DI2 [s]","DI2 activation[s]"},
/* 149 FC_LBL_1_03                         */ { "Disattivazione DI2 [s]","DI2 deactivation [s]"},
/* 150 FC_LBL_1_04                         */ { "Attivazione DI3 [s]","DI3 activation [s]"},
/* 151 FC_LBL_1_05                         */ { "Disattivazione DI3 [s]","DI3 deactivation [s]"},
/* 152 FC_GB_2_STR_USCITE                  */ { "Uscite","Output"},
/* 153 FC_LBL_2_00                         */ { "AO2","AO2"},
/* 154 FC_LBL_2_01                         */ { "TR2","TR2"},
/* 155 FC_LBL_2_02                         */ { "TR1","TR1"},
/* 156 FC_LBL_2_03                         */ { "CONFIGURAZIONE USCITE","OUTPUT_CONFIGURATION"},
/* 157 FC_CMB_2_00                         */ { "TR1 batt. el. + TR2 batt. H2O fredda ON/OFF","TR1 el. heater + TR2 H2O cooling coil ON/OFF"},
/* 158 FC_CMB_2_01                         */ { "TR1 batt. el. + TR2 batt. H2O fredda PWM","TR1 el. heater + TR2 H2O cooling coil PWM"},
/* 159 FC_CMB_2_02                         */ { "TR1 batt. el. + TR2 batt. H2O fredda 0-10V","TR1 el. heater + TR2 H2O cooling coil 0-10V"},
/* 160 FC_CMB_2_03                         */ { "TR1 batt. H2O calda PWM + TR2 batt. H2O fredda PWM","TR1 H2O heating coil PWM + TR2 H2O cooling coil PWM"},
/* 161 FC_CMB_2_04                         */ { "TR1 batt. H2O calda PWM + TR2 batt. H2O fredda ON/OFF","TR1 H2O heating coil PWM + TR2 H2O cooling coil ON/OFF"},
/* 162 FC_CMB_2_05                         */ { "TR1 batt. H2O calda PWM + TR2 batt. H2O fredda 0-10V","TR1 H2O heating coil PWM + A2O H2O cooling coil 0-10V"},
/* 163 FC_CMB_2_06                         */ { "AO2 batt. H2O calda 0-10V + TR2 batt. H2O fredda PWM","AO2 H2O heating coil 0-10V + TR2 H2O cooling coil PWM"},
/* 164 FC_CMB_2_07                         */ { "AO2 batt. H2O calda 0-10V + TR2 batt. H2O fredda ON/OFF","AO2 H2O heating coil 0-10V + TR2 H2O cooling coil ON/OFF"},
/* 165 FC_CMB_2_08                         */ { "TR2 batt. promiscua PWM + TR1 valvola change over ON/OFF","TR2 promiscuous coil PWM + TR1 change over valve ON/OFF"},
/* 166 FC_CMB_2_09                         */ { "AO2 batt. promiscua 0-10V + TR1 valvola change over ON/OFF","AO2 promiscuous coil 0-10V + TR1 change over valve ON/OFF"},
/* 167 FC_CMB_2_10                         */ { "TR1 batt. el. + TR2 batt. H2O fredda ON/OFF + AO2 serr. mod.","TR1 el. heater + TR2 H2O cooling coil ON/OFF + AO2 damper. mod."},
/* 168 FC_CMB_2_11                         */ { "TR1 batt. el. + TR2 batt. H2O fredda PWM + AO2 serr. mod.","TR1 el. heater + TR2 H2O cooling coil PWM + AO2 damper. mod."},
/* 169 FC_CMB_2_12                         */ { "TR1 batt. el. + TR2 batt. H2O fredda 0-10V + AO2 serr. mod.","TR1 el. heater + TR2 H2O cooling coil 0-10V + AO2 damper. mod."},
/* 170 FC_CMB_2_13                         */ { "TR1 batt H2O calda PWM + TR2 batt. H2O fredda PWM + AO2 serr. mod.","TR1 batt H2O calda PWM + TR2 batt. H2O fredda PWM + AO2 damper. mod."},
/* 171 FC_CMB_2_14                         */ { "TR1 batt H2O calda PWM + TR2 batt. H2O fredda ON/OFF + AO2 serr. mod.","TR1 batt H2O calda PWM + TR2 batt. H2O fredda ON/OFF + AO2 damper. mod."},
/* 172 FC_CMB_2_15                         */ { "TR2 batt promiscua PWM + TR1 valvola change over ON/OFF + AO2 serr. mod.","TR2 promiscuous coil PWM + TR1 change over valve ON/OFF + AO2 damper mod."},
/* 173 FC_RB_2_00_0                        */ { "OFF","OFF"},
/* 174 FC_RB_2_00_1                        */ { "SERRANDA","DAMPER"},
/* 175 FC_RB_2_00_2                        */ { "VALVOLA","VALVE"},
/* 176 FC_RB_2_01_0                        */ { "ON-OFF","ON-OFF"},
/* 177 FC_RB_2_01_1                        */ { "PWM","PWM"},
/* 178 FC_RB_2_02_0                        */ { "OFF","OFF"},
/* 179 FC_RB_2_02_1                        */ { "ON ","ON"},
/* 180 FC_GB_3_SEGN_FILTRO_SPORCO          */ { "Segnalazione filtro sporco","Dirty filter SW signal"},
/* 181 FC_LBL_3_00                         */ { "Abilitazione","Enabling"},
/* 182 FC_LBL_3_01                         */ { "Tempo segnalazione [giorni]","Reporting time [days]"},
/* 183 FC_LBL_3_02                         */ { "Reset contatore","Counter reset"},
/* 184 FC_BTN_3_00                         */ { "RESET","RESET"},
/* 185 FC_TAB_1                            */ { "Regolazioni","Regulations"},
/* 186 FC_GB_4_REGOLAZIONE_RISC            */ { "Regolazione riscaldamento","Heating settings"},
/* 187 FC_LBL_4_00                         */ { "Zona morta riscaldamento H.D.Z. [C°]","Heating dead zone H.D.Z. [C°]"},
/* 188 FC_LBL_4_01                         */ { "Banda di regolazione risc.E.H.B. [C°]","El. heater heating band E.H.B. [C°]"},
/* 189 FC_LBL_4_02                         */ { "KI regolazione riscaldamento [%]","KI heating regulation [%]"},
/* 190 FC_LBL_4_03                         */ { "Periodo modulazione PWM  [s]","EL. heater éWM modulation period"},
/* 191 FC_LBL_4_04                         */ { "Minimo duty cycle resistenza [%]","Minimum duty cycle [%]"},
/* 192 FC_LBL_4_05                         */ { "Massimo duty cycle resistenza [%]","Maximum duty cycle [%]"},
/* 193 FC_LBL_4_06                         */ { "Abilitazioni allarmi resistenza elettrica","El. heater alarms enabling"},
/* 194 FC_GB_5_REGOLAZIONE_FREDDO          */ { "Regolazione raffreddamento","Cooling settings"},
/* 195 FC_LBL_5_00                         */ { "Zona morta raffreddamento C.D.Z. [C°]","Cooling dead zone  C.D.Z. [C°]"},
/* 196 FC_LBL_5_01                         */ { "Banda di reg. valvola raff. V.C.B [C°]","Valve actuator cooling band V.C.B. [C°]"},
/* 197 FC_LBL_5_02                         */ { "KI regolazione valvola raffreddamento [%]","KI cooling valve regulation [%]"},
/* 198 FC_LBL_5_03                         */ { "Isteresi valvola ON-OFF C.HY. [C°]","ON-OFF valve cool. Hyser. C.HY. [C°]"},
/* 199 FC_LBL_5_04                         */ { "Periodo modulazinoe PWM valvola  [s]","PWM valve modulation period"},
/* 200 FC_LBL_5_05                         */ { "Minimo duty cycle valvola [%]","Minimum valve duty cycle [%]"},
/* 201 FC_LBL_5_06                         */ { "Massimo duty cycle valvola [%]","Maximum valve duty cycle [%]"},
/* 202 FC_LBL_5_07                         */ { "Durata ‘raffreddamento rapido’ [m]","'Quick cooleng”’duration [s]"},
/* 203 FC_LBL_5_08                         */ { "Potenza ‘raffreddamento rapido’ [%]","'Quick cooleng”’power [%]"},
/* 204 FC_GB_6_REGOLAZIONE_VENTILATORE     */ { "Regolazione ventilatore","Fan settinhg"},
/* 205 FC_LBL_6_00                         */ { "Modalita venrilaz. Min. In zona morta","Min. ventilation mode in dead zone"},
/* 206 FC_LBL_6_01                         */ { "Abilitazione ventilazione manuale","manual ventilation enabling"},
/* 207 FC_LBL_6_02                         */ { "Tempo post ventilazinoe [s]","Post ventilation time [s]"},
/* 208 FC_LBL_6_03                         */ { "Tensione ventilatore allo 0% (min. Speed) [V]","Fan voltage at 0% (min speed)  [V}"},
/* 209 FC_LBL_6_04                         */ { "Tensione ventilatore allo 100% (max. Speed) [V]","Fan voltage at 100% (max. speed)  [V}"},
/* 210 FC_LBL_6_05                         */ { "Tensione minima attivazine bentilatore Vact, [V]","Minimum fan activaton voltage Vac. [V]"},
/* 211 FC_LBL_6_06                         */ { "Minimo numero giri in ON [giri/minuto]","Minumun fan turns in IN [rpm]"},
/* 212 FC_LBL_6_07                         */ { "Banda di regolazione vent. In risc. F.H.B. [C°]","Fan heating regulation band F.H.B. [C°]"},
/* 213 FC_LBL_6_08                         */ { "Banda di regolazione vent. In raff. F.C.B. [C°]","Fan cooling regulation band F.C.B. [C°]"},
/* 214 FC_LBL_6_09                         */ { "KI regolazione raff./risc. [%]","KI fan cool/heat. Regulation [%]"},
/* 215 FC_GB_7_REGOLAZIONE_SERRANDA_FA     */ { "Regolazione serranda fresh air","Fresh air damper settings"},
/* 216 FC_LBL_7_00                         */ { "Modalità gestione serranda","Damper managment mode"},
/* 217 FC_LBL_7_01                         */ { "Setpoint CO₂CO2.S.P. [ppm]","CO₂setpoint CO2.S.P. [ppm]"},
/* 218 FC_LBL_7_02                         */ { "Banda regolazione CO₂CO2.B. [ppm]","CO₂ regulation band CO2.B. [ppm]"},
/* 219 FC_LBL_7_03                         */ { "Setpoint VOC VOC.S.P. [%]","VOC setpoint VOC.S.P. [ppm]"},
/* 220 FC_LBL_7_04                         */ { "Banda regolazione VOC VOC.B. [%]","VOC regulation band VOC.B. [ppm]"},
/* 221 FC_LBL_7_05                         */ { "Apertura mimima serranda [%]","Minimjum damper opening [%]"},
/* 222 FC_LBL_7_06                         */ { "Apertura massima serranda [%]","Maximum damper opening [%]"},
/* 223 FC_LBL_7_07                         */ { "Tensione alla portata minima  [V]","Voltage at min. air flow [V]"},
/* 224 FC_LBL_7_08                         */ { "Tensione alla portata massima [V]","Voltage at max. air flow [V]"},
/* 225 FC_LBL_7_09                         */ { "Portata minima [m³/h]","Mimimum air flow [m³/h]"},
/* 226 FC_LBL_7_10                         */ { "Portata massima [m³/h]","Maximum air flow [m³/h]"},
/* 227 FC_LBL_7_11                         */ { "Setpoint portata confort mode [m³/h]","Confort mode air flow set point  [m³/h]"},
/* 228 FC_LBL_7_12                         */ { "Setpoint portata economy [m³/h]","Economy mode air flow set point  [m³/h]"},
/* 229 FC_CB_7_00                          */ { "CO₂","CO₂"},
/* 230 FC_CB_7_01                          */ { "Economy","Economy "},
/* 231 FC_CB_7_02                          */ { "Damper","Damper"},
/* 232 FC_TAB_2                            */ { "Impostazioni","Settings"},
/* 233 FC_GB_8_IMPOSTAZIONE_SONDA          */ { "Impostazione sonda e setpoint temperatura","Regulation probe and temperature setpoint setting"},
/* 234 FC_LBL_8_00                         */ { "Tipo sonda regolazione","Regulation probe"},
/* 235 FC_LBL_8_01                         */ { "Setpoint di temperatura di default [C°]","Default temperature setpoint [C°]"},
/* 236 FC_LBL_8_02                         */ { "Deviazione max. setpoint di default [C°]","Max default setpoin deviation [C°]"},
/* 237 FC_CB_8_00_00                       */ { "",""},
/* 238 FC_CB_8_00_01                       */ { "termostato ambiente","room thermostat"},
/* 239 FC_CB_8_00_02                       */ { "NTC1 interna","NTC1 internal"},
/* 240 FC_CB_8_00_03                       */ { "NTC2 ripresa","NTC2 return"},
/* 241 FC_CB_8_00_04                       */ { "NTC2 mandata","NTC2 supply"},
/* 242 FC_CB_8_00_05                       */ { "Modbus (domotica)","Modbus (domotic)"},
/* 243 FC_CB_8_01_00                       */ { "1) aumento xona morta e ris.bande","1)"},
/* 244 FC_CB_8_01_01                       */ { "2) aumento zona morta","2)"},
/* 245 FC_CB_8_01_02                       */ { "3) OFF","3) OFF"},
/* 246 FC_GB_9_SENSORE_PRESSIONE           */ { "Sensore pressione","Pressure sensor"},
/* 247 FC_LBL_9_00                         */ { "Soglia intasamento filtro [Pa]","Filter clogging threshold (Pa)"},
/* 248 FC_LBL_9_01                         */ { "Isteresi soglia intasamento filtro [Pa]","Filter clogging th hysteresis (Pa)"},
/* 249 FC_LBL_9_02                         */ { "Soglia alta pressione [Pa]","Hi pressure alarm threshold [Pa]"},
/* 250 FC_LBL_9_03                         */ { "Istsresi soglia alta pressione [Pa]","Hi pressure alarm th. Hysteresis [Pa]"},
/* 251 FC_LBL_9_04                         */ { "Soglia bassa pressione [Pa]","Low pressure alarm threshold [Pa]"},
/* 252 FC_LBL_9_05                         */ { "Istsresi soglia bassa pressione [Pa]","Low pressure alarm th. Hysteresis [Pa]"},
/* 253 FC_LBL_9_06                         */ { "Ritardo abil. Allarme bassa pressione [s]","Low pressure alarm enabling delay [s]"},
/* 254 FC_GB_10_TEMP_INTERNA               */ { "Gestione temperatura interna","Internal temperature management"},
/* 255 FC_LBL_10_00                        */ { "Soglia di sicurezza [C°]","Safety temperature threshold [C°]"},
/* 256 FC_LBL_10_01                        */ { "Isteresi temperatura di sicurezza [C°]","Safety temperature hysteresis [C°]"},
/* 257 FC_GB_11_TEMP_MADATA                */ { "Limiti temperatura mandata","Supply temperature limits"},
/* 258 FC_LBL_11_00                        */ { "Setpoint limite minimo L.L.S.P. [C°]","Low limit setpoint L.L.S.P. [C°]"},
/* 259 FC_LBL_11_01                        */ { "Isteresi limite minimo C.L.HY. [C°]","Cooling limit hysteresis C.L.HY. [C°]"},
/* 260 FC_LBL_11_02                        */ { "Setpoint limite massimo H.L.S.P. [C°]","Hi limit setpoint H.L.S.P. [C°]"},
/* 261 FC_LBL_11_03                        */ { "Banda regolazione limiti L.B. [C°]","Limits regulation band  L.B. [C°]"},
/* 262 FC_GB_12_RAMPA_VENTIL               */ { "Funzione rampa ventilatore","Fan ramp function"},
/* 263 FC_LBL_12_00                        */ { "Abilitazione","Enabling"},
/* 264 FC_LBL_12_01                        */ { "Tempo di rampa [s]","Ramp time [s]"},
/* 265 FC_TAB_3                            */ { "Impostazioni MODBUS","MODBUS settings"},
/* 266 FC_GB_13_IMPOSTAZIONI_RETE          */ { "Impostazioni rete","Network setting"},
/* 267 FC_LBL_13_00                        */ { "Tipologia dispositivo","Device type"},
/* 268 FC_LBL_13_01                        */ { "Indirizzo","Address"},
/* 269 FC_LBL_13_02                        */ { "Baudrate","Baudrate"},
/* 270 FC_LBL_13_03                        */ { "Parità","Parity"},
/* 271 FC_LBL_13_04                        */ { "Bit stop","Stop bit"},
/* 272 FC_RB_LBL_13_00                     */ { "Master","Master"},
/* 273 FC_RB_LBL_13_01                     */ { "Slave","Slave"},
/* 274 FC_CB_13_00_2400                    */ { "2400","2400"},
/* 275 FC_CB_13_00_4800                    */ { "4800","4800"},
/* 276 FC_CB_13_00_9600                    */ { "9600","9600"},
/* 277 FC_CB_13_00_19200                   */ { "19200","19200"},
/* 278 FC_CB_13_00_38400                   */ { "38400","38400"},
/* 279 FC_CB_13_00_57600                   */ { "57600","57600"},
/* 280 FC_CB_13_00_115200                  */ { "115200","115200"},
/* 281 FC_CB_13_01_00_NESSUNA              */ { "Nessuna","None"},
/* 282 FC_CB_13_01_00_PARI                 */ { "Pari","Even"},
/* 283 FC_CB_13_01_00_DISPARI              */ { "Dispari","Odd"},
/* 284 FC_CB_13_02_BITSTOP_1               */ { "1","1"},
/* 285 FC_BC_13_02_BITSTOP_2               */ { "2","2"},
/* 286 FC_GB15_RegolazioneChangeOver       */ { "Regolazione Change Over","Change over setiing"},
/* 287 FC_LBL_15_00                        */ { "Isteresi valv. ch.ov. ON-OFF CO.HY [C°]","ON-OFF ch.ov. valve Histeresis CH.HY [C°]"},
/* 288 FC_LBL_15_01                        */ { "Logica valvola","Valve logic"},
/* 289 FC_LBL_15_02                        */ { "Tempo ritardo attivazione uscite risc./raff. [s]","Heating and cooling outputs activation delay time [s]"},
/* 290 FC_CB_15_00                         */ { "Raffreddamento = 230 V","Cooling = 230 V"},
/* 291 FC_CB_15_01                         */ { "Raffreddamento = 0 V","Cooling = 0 V"},
/* 292 FC_GB17_ECONOMYMODE                 */ { "Economy mode","Economy mode"},
/* 293 FC_LBL_17_00_TED1                   */ { "Tipo ecomomy DI1","DI1 economy type"},
/* 294 FC_LBL_17_01_TED2                   */ { "Tipo ecomomy DI2","DI2 economy type"},
/* 295 FC_LBL_17_02_TED3                   */ { "Tipo ecomomy DI3","DI3 economy type"},
/* 296 FC_LBL_17_03_PRIORITA               */ { "Priorità economy","Economy priority DI"},
/* 297 FC_LBL_17_04_HDZI1                  */ { "Incremento zona morta risc. in economy mode TIPO 1 H.D.Z.I.1  [C°]","Heating dead zone increase in TYPE 1 economy mode H.D.Z.I 1 [C°]"},
/* 298 FC_LBL_17_05_CDZI1                  */ { "Incremento zona morta raff. in economy mode TIPO 1 C.D.Z.I.1  [C°]","Cooling dead zone increase in TYPE 1 economy mode C.D.Z.I 1 [C°]"},
/* 299 FC_LBL_17_06_HDZI2                  */ { "Incremento zona morta risc. in economy mode TIPO 1 H.D.Z.I.2  [C°]","Heating dead zone increase in TYPE 2 economy mode H.D.Z.I 2 [C°]"},
/* 300 FC_LBL_17_07_CDZI2                  */ { "Incremento zona morta raff. in economy mode TIPO 1 C.D.Z.I.2  [C°]","Cooling dead zone increase in TYPE 2 economy mode C.D.Z.I 2 [C°]"},
/* 301 FC_CB_17_00_TIPO_ECONOMY_00         */ { "1) TIPO 1 aumrnto zona morta 1","1) TYPE 1 dead zone inc. 1"},
/* 302 FC_CB_17_00_TIPO_ECONOMY_01         */ { "2) TIPO 2 aumrnto zona morta 2","2) TYPE 1 dead zone inc. 2"},
/* 303 FC_CB_17_00_TIPO_ECONOMY_02         */ { "3) TIPO 3 OFF","3) TYPE 3 OFF"},
/* 304 FC_CB_17_00_TIPO_ECONOMY_03         */ { "4) TIPO 4 ventilazione minima","4) TYPE 4 minimum ventilation"},
/* 305 FC_CB_17_01_PRIOROTA_00             */ { "1) DI1, DI2, DI3","1) DI1, DI2, DI3"},
/* 306 FC_CB_17_01_PRIOROTA_01             */ { "2) DI1, DI3, DI2","2) DI1, DI3, DI2"},
/* 307 FC_CB_17_01_PRIOROTA_02             */ { "3) DI2,DI1,DI3","3) DI2,DI1,DI3"},
/* 308 FC_CB_17_01_PRIOROTA_03             */ { "4) DI2, DI3, DI1","4) DI2, DI3, DI1"},
/* 309 FC_CB_17_01_PRIOROTA_04             */ { "5) DI3, DI1, DI2","5) DI3, DI1, DI2"},
/* 310 FC_CB_17_01_PRIOROTA_05             */ { "6) DI3, DI2, DI1","6) DI3, DI2, DI1"},
/* 311 FC_GB16_ExtPressSens                */ { "Sensore di pressione esterno","Extarnal pressure sensor"},
/* 312 FC_LBL_16_00_VoltageRange           */ { "Range tensione [V}","Voltage range [V]"},
/* 313 FC_LBL_16_01_PressRange             */ { "Range pressione  [Pa]","Pressure range [Pa]"},
/* 314 FC_LBL_16_02_AlarmTreshold          */ { "Soglia allarme [V}","Alarm threshold [V]"},
/* 315 FC_CB_16_00_RANGETENSIONE_00        */ { "0..10","0..10"},
/* 316 FC_CB_16_00_RANGETENSIONE_01        */ { "2..10","2..10"},
/* 317 FC_CB_16_01_RANGEPRESSIONE_00       */ { "0..25","0..25"},
/* 318 FC_CB_16_01_RANGEPRESSIONE_01       */ { "0..50","0..50"},
/* 319 FC_CB_16_01_RANGEPRESSIONE_02       */ { "0..100","0..100"},
/* 320 FC_CB_16_01_RANGEPRESSIONE_03       */ { "0..250","0..250"},
/* 321 FC_CB_16_01_RANGEPRESSIONE_04       */ { "0..500","0..500"},
/* 322 FC_CB_16_01_RANGEPRESSIONE_05       */ { "0..1000","0..1000"},




// ---------------------------- T1
/* 327 T1_GB_0                             */ { "Impostazione LED","LED setting"},
/* 328 T1_LBL_0_00                         */ { "Colore","Color"},
/* 329 T1_LBL_0_01                         */ { "Luminosità piena","Full brightness"},
/* 330 T1_LBL_0_02                         */ { "Tempo accensione","ON Time"},
/* 331 T1_LBL_0_03                         */ { "Luminosita’ intermedia","Intermediate brightness "},
/* 332 T1_LBL_0_04                         */ { "Tempo spegnimento","OFF Time"},
/* 333 T1_GB_1                             */ { "Impostazione termostato","Thermostat setting"},
/* 334 T1_LBL_1_00                         */ { "Tipologia termostato","Thermostat type"},




// ------------------------------ T2

/* 335 T2_GB_0                             */ { "Impostazione LED","LED setting"},
/* 336 T2_LBL_0_00                         */ { "Colore LED comandi","Command LED color"},
/* 337 T2_LBL_0_01                         */ { "Colore LED ventola","Fan LED color"},
/* 338 T2_LBL_0_02                         */ { "Colore LED caldo","Warm LED color"},
/* 339 T2_LBL_0_03                         */ { "Colore LED centrali","Central LED color"},
/* 340 T2_LBL_0_04                         */ { "Colore LED freddo","Cold LED color"},
/* 341 T2_LBL_0_05                         */ { "Modello termostato","Termostat model"},
/* 342 T2_CB_0_00                          */ { "6 tasti","6 switches"},
/* 343 T2_CB_0_01                          */ { "5 tasti quick cooling","5 switches quick cooling"},
/* 344 T2_CB_0_02                          */ { "5 tasti","5 switches"},
/* 345 T2_CB_0_03                          */ { "4 tasti","4 switches"},
/* 346 T2_CB_0_04                          */ { "3 tasti","3 switches"},
/* 347 T2_CB_0_05                          */ { "2 tasti","2 switches"},
/* 348 T2_LBL_1_01                         */ { "Ablilta/Disabilita","Enable/Disable"},



// ------------------------------ MASTER NETWORK

/* 349 MNET_H_DISPOSITIVO                  */ { "Dispositivo","Device"},
/* 350 MNET_H_INDIRIZZO                    */ { "Indirizzo","Address"},
/* 351 MNET_H_MATRICOLA                    */ { "Matricola","Serial number"},
/* 352 MNET_H_STATO                        */ { "Stato","Status"},
/* 353 MNET_B_RESET                        */ { "Reset rete","Network reset"},
/* 354 MNET_B_UPDATE                       */ { "Aggiorna rete","Network update"},
/* 355 MNET_B_FIX                          */ { "Salva rete","Fix network"},
/* 356 MNET_B_ESCI                         */ { "Esci","Exit"},
/* 357 MNET_MSG_ERROR_1                    */ { "Non è possibile cambiare l’indirizzo al MASTER","  It is not possible to change the address to the MASTER"},
/* 358 MNET_MSG_ERROR                      */ { "Errore","Error"},
/* 359 MNET_MSG_ERROR_2                    */ { "Errore nella configurazione della rete","Error while network configuration"},
/* 360 MNET_MSG_RESTART                    */ { "Riavvia il MASTER","Restart MASTER"},
/* 361 MNET_MSG_SAVED                      */ { "Dati salvati correttamente","Data successfully saved "},
/* 362 MNET_MSG_DNOTSAVED                  */ { "La nuova configurazione non è stata salvata. Esci ugualmente ?","The new configuration has not been saved. Are you still going out?"},
/* 363 MNET_MSG_INFO                       */ { "Info","Info"},
/* 364 MNET_MSG_WARNING                    */ { "Attenzione!!","Warning!!"},
/* 365 MNET_MSG_NO_PRINCIPALE              */ { "Almeno un elemento deve essere etichettato come principale","At least one element must be tagged as principal "},
/* 366 MNET_H_SW_RELEASE                   */ { "Versione software","Software release"},
/* 367 MNET_MSG_RESATART                   */ { "Riavviare il master","Please restart master"},

// -------------------------------  STARTUP
/* 368 STARTUP_DISCONNSSIONE_INCORSO       */ { "DISCONNESSIONE ….","UNCONNECTING …."},
/* 369 STARTUP_DISCONNESSO                 */ { "DISCONNESSO","UNCONNECTED"},
/* 370 STARTUP_CONNECTION_ERROR            */ { "USB errore connessione","USB connection error"},


};
		// <FINE STRINGHE>

		// GENERICO
		static string[,] generico = new string[(int)indice.TOTALE - (int)indice.NUM_OF_STRING - 1, NUMERO_LINGUE] {
		/*   ESSAGGIO          */ {"Errore","Error"},
		/*   ESSAGGIO          */ {"Dati non compatibili","Not compatible data"},
		/* INVALID_SERIAL_NUMBER */  {"il quinto carattere della matricola non corrisponde con il dispositivo","Not compatible data"},
};
        static string[] vocabolario = new string[] { "³", "°", "ª", "±", "²", "\"", "à"};


        static public string getStr(indice ind)
        {
			if((int)ind > (int)indice.NUM_OF_STRING)
			{
				int ix = (int)ind - (int)indice.NUM_OF_STRING - 1;

                return generico[ix, Linguaggio];

            } else
				return localizzazioni[(int)ind, Linguaggio];
        }


        static public string getStr1_8(int x)
        {
            return getStr((indice)x);
        }











    }
}