using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace configuratore.statoCassette
{
    public class lStat
    {
        public enum Indice
        {
/* 0 */ TXT_gpGestionePortata,
/* 1 */ TXT_gpRegolazioneTempAmb,
/* 2 */ TXT_gpInfoMatricola,
/* 3 */ TXT_gpSegnalazioni,
/* 4 */ TXT_gbAllarmi,
/* 5 */ TXT_gbPLC,
/* 6 */ TXT_gbForzature,
/* 7 */ LBL_00_PortatataIstantanea,
/* 8 */ LBL_01_deltaPortatataIstantanea,
/* 9 */ LBL_02_PortataMinima,
/* 10 */ LBL_03_deltaPressioneMinima,
/* 11 */ LBL_04_PortataMassima,
/* 12 */ LBL_05_deltaPressioneMassima,
/* 13 */ LBL_06_PortataMinimaSicurezza,
/* 14 */ LBL_07_deltaPressioneMinimaSicurezza,
/* 15 */ LBL_08_MofulazioneSerranda,
/* 16 */ LBL_09_LetturaPosizioneSerranda,
/* 17 */ LBL_10_TemperaturaAnbienta,
/* 18 */ LBL_11_SetpointTemperatura,
/* 19 */ LBL_12_ResistenzaElettrica,
/* 20 */ LBL_13_DCMassimoIstantaneo,
/* 21 */ LBL_14_RiduzioneRiscaldamento,
/* 22 */ LBL_15_TemperaturaInterna,
/* 23 */ LBL_16_TemperaturaMandata,
/* 24 */ LBL_20_Matricola,
/* 25 */ LBL_21_IndirizzoSlave,
/* 26 */ LBL_30_ModalitaOffdaRemoto,
/* 27 */ LBL_31_ModalitaEcoDaTermostato,
/* 28 */ LBL_32_ModalitaEconDaID1,
/* 29 */ LBL_33_ModalitaEconDaID2,
/* 30 */ LBL_34_ModalitaEconDaID3,
/* 31 */ LBL_35_ModalitaEcondaAnal,
/* 32 */ LBL_36_ModalitaEcondaPLCinRete,
/* 33 */ LBL_37_ModalitaEcondaMODBUS,
/* 34 */ LBL_38_OffResistPrimaSoglia,
/* 35 */ LBL_39_LimiteMassimoTMandata,
/* 36 */ LBL_3A_RiduzuineDCMaxResPerPort,
/* 37 */ LBL_40_SondaTempInterna,
/* 38 */ LBL_41_SondaTempMandata,
/* 39 */ LBL_42_SondaTempAmbiente,
/* 40 */ LBL_43_AltaTemIntSecondaSoglia,
/* 41 */ LBL_44_InterventoTermResistenza,
/* 42 */ LBL_45_TermStanzaNonCollegato,
/* 43 */ LBL_46_SondaTemStanza,
/* 44 */ LBL_47_CircResistenzaAperta,
/* 45 */ LBL_48_CircInnescoRes,
/* 46 */ LBL_49_Serranda,
/* 47 */ LBL_4A_SensorePressione,
/* 48 */ LBL_4B_PortataBassa,
/* 49 */ LBL_50_TemperaturaScheda,
/* 50 */ LBL_51_FrequenzaRete,
/* 51 */ LBL_52_24Volt,
/* 52 */ LBL_53_RiduzioneTemperatura,
/* 53 */ LBL_60_ApertutaSerranda,
/* 54 */ LBL_61_ComadoResistenza,
/* 55 */ LBL_62_RichMaxRaffreddamento,
/* 56 */ LBL_09_TensioneSerranda,
/* 57 */ LBL_63_MasterSlave,
/* 58 */ LBL_54_TensioneRete,
/* 59 */ LBL_55_RS485_O_ERR,
/* 60 */ LBL_56_TEMP_TERMOSTATO,
/* 61 */ LBL_57_ADJTEMPTERM,
/* 62 */ LBL_58_PRIMARYDEVICE,

            // ----------------------------------------------------------
/* 63 */ FS_GB_0_FANCOIL,
/* 64 */ FS_LBL_0_00,
/* 65 */ FS_LBL_0_01,
/* 66 */ FS_LBL_0_02,
/* 67 */ FS_LBL_0_03,
/* 68 */ FS_GB_1_INGRESSI,
/* 69 */ FS_LBL_1_00,
/* 70 */ FS_LBL_1_01,
/* 71 */ FS_LBL_1_02,
/* 72 */ FS_LBL_1_03,
/* 73 */ FS_LBL_1_04,
/* 74 */ FS_LBL_1_05,
/* 75 */ FS_LBL_1_06,
/* 76 */ FS_GB_2_REGOLAZIONE,
/* 77 */ FS_LBL_2_00,
/* 78 */ FS_LBL_2_01,
/* 79 */ FS_LBL_2_02,
/* 80 */ FS_LBL_2_02Sub,
/* 81 */ FS_LBL_2_03,
/* 82 */ FS_LBL_2_03Sub,
/* 83 */ FS_LBL_2_04,
/* 84 */ FS_LBL_2_04Sub,
/* 85 */ FS_LBL_2_05,
/* 86 */ FS_LBL_2_05Sub,
/* 87 */ FS_LBL_2_06,
/* 88 */ FS_LBL_2_06Sub,
/* 89 */ FS_LBL_2_07,
/* 90 */ FS_LBL_2_08,
/* 91 */ FS_LBL_2_09,
/* 92 */ FS_LBL_2_10,
/* 93 */ FS_GB_3_STATI,
/* 94 */ FS_LBL_3_00,
/* 95 */ FS_LBL_3_01,
/* 96 */ FS_LBL_3_02,
/* 97 */ FS_LBL_3_03,
/* 98 */ FS_LBL_3_04,
/* 99 */ FS_LBL_3_05,
/* 100 */ FS_LBL_3_06,
/* 101 */ FS_LBL_3_07,
/* 102 */ FS_LBL_3_08,
/* 103 */ FS_LBL_3_09,
/* 104 */ FS_LBL_3_10,
/* 105 */ FS_LBL_3_11,
/* 106 */ FS_LBL_3_12,
/* 107 */ FS_LBL_3_13,
/* 108 */ FS_LBL_3_14,
/* 109 */ FS_GB_4_ALLARMI,
/* 110 */ FS_LBL_4_00,
/* 111 */ FS_LBL_4_01,
/* 112 */ FS_LBL_4_02,
/* 113 */ FS_LBL_4_03,
/* 114 */ FS_LBL_4_04,
/* 115 */ FS_LBL_4_05,
/* 116 */ FS_LBL_4_06,
/* 117 */ FS_LBL_4_07,
/* 118 */ FS_LBL_4_08,
/* 119 */ FS_LBL_4_09,
/* 120 */ FS_LBL_4_10,
/* 121 */ FS_LBL_4_11,
/* 122 */ FS_LBL_4_12,
/* 123 */ FS_LBL_4_13,
/* 124 */ FS_LBL_4_14,
/* 125 */ FS_LBL_4_15,
/* 126 */ FS_LBL_4_16,
/* 127 */ FS_LBL_4_17,
/* 128 */ FS_LBL_4_18,
/* 129 */ FS_LBL_4_19,
/* 130 */ FS_LBL_4_20,
/* 131 */ FS_GB_5_FORZATURE,
/* 132 */ FS_LBL_5_00,
/* 133 */ FS_LBL_5_01,
/* 134 */ FS_LBL_5_02,
/* 135 */ FS_LBL_5_03,



// -------------------------------------- T1
/* 136 */ T1_GB_S0,
/* 137 */ T1_LBL_S0_00,
/* 138 */ T1_LBL_S0_01,
/* 139 */ T1_LBL_S0_02,
/* 140 */ T1_LBL_S0_03,
/* 141 */ T1_LBL_S0_04,
/* 142 */ T1_LBL_S0_05,
/* 143 */ T1_LBL_S0_06,
/* 144 */ T1_GB_S1,
/* 145 */ T1_GB_S2,
/* 146 */ T1_LBL_S2_00,
/* 147 */ T1_LBL_S2_01,
/* 148 */ T1_LBL_S2_02,





// ----------------------------------------- T2
/* 149 */ T2_LBL_S0_00,
/* 150 */ T2_LBL_S0_01,
/* 151 */ T2_LBL_S0_02,
/* 152 */ T2_LBL_S0_03,
/* 153 */ T2_LBL_S0_04,
/* 154 */ T2_LBL_S0_05,
/* 155 */ T2_LBL_G2_00,
/* 156 */ T2_LBL_S2_00,
/* 157 */ T2_LBL_S2_01,






            NUM_OF_STRING,
        }

        static string[,] localizzazioni = new string[(int)Indice.NUM_OF_STRING, loca.NUMERO_LINGUE] {
/* 0 TXT_gpGestionePortata                     */ { "Gestione portata","Flow rate managment"},
/* 1 TXT_gpRegolazioneTempAmb                  */ { "Regolazione temperatura ambiente","Room temperature refulations"},
/* 2 TXT_gpInfoMatricola                       */ { "",""},
/* 3 TXT_gpSegnalazioni                        */ { "Segnalazioni","States"},
/* 4 TXT_gbAllarmi                             */ { "Allarmi","Alarms"},
/* 5 TXT_gbPLC                                 */ { "PLC","PLC"},
/* 6 TXT_gbForzature                           */ { "Forzature","Overrides"},
/* 7 LBL_00_PortatataIstantanea                */ { "Portata istantanea [l/S]","Instant flow rate [l/S]"},
/* 8 LBL_01_deltaPortatataIstantanea           */ { "Delta pressione istantanea [Pa]","Instantaneous delta pressure [Pa]"},
/* 9 LBL_02_PortataMinima                      */ { "Portata minima [l/S]","Minimum flow rate [l/S]"},
/* 10 LBL_03_deltaPressioneMinima               */ { "Delta pressione  minima [Pa]","Minimum delta pressure [Pa]"},
/* 11 LBL_04_PortataMassima                     */ { "Portata massima [l/S]","Maximum flow rate [l/S]"},
/* 12 LBL_05_deltaPressioneMassima              */ { "Delta pressione  massima [Pa]","Maximum delta pressure [Pa]"},
/* 13 LBL_06_PortataMinimaSicurezza             */ { "Portata minima sicurezza [l/S]","Minimum safety flow rate [l/S]"},
/* 14 LBL_07_deltaPressioneMinimaSicurezza      */ { "Delta pressione  minima sicurezza [Pa]","Safety delta pressure [Pa]"},
/* 15 LBL_08_MofulazioneSerranda                */ { "Modulazione serranda [%]","Damper modulation [%] "},
/* 16 LBL_09_LetturaPosizioneSerranda           */ { "Lettura posizione serranda [%]","Damper position [%] "},
/* 17 LBL_10_TemperaturaAnbienta                */ { "Temperatura ambiente [C°]","Room temperature [C°]"},
/* 18 LBL_11_SetpointTemperatura                */ { "Setpoint temperatura [C°]","Temperature setpoint [C°]"},
/* 19 LBL_12_ResistenzaElettrica                */ { "Resistenza elettrica [%]","Electric heater [%]"},
/* 20 LBL_13_DCMassimoIstantaneo                */ { "DC massimo istantaneo [%]\nin f[Q]","Maximum istantaneouse DC [%]\nin f[Q]"},
/* 21 LBL_14_RiduzioneRiscaldamento             */ { "Riduzione riscaldamento [%]\n[T.Mand.]","Heating reduction [%]\n[Supply T.]"},
/* 22 LBL_15_TemperaturaInterna                 */ { "Temperatura interna","Internal temperature [C°]"},
/* 23 LBL_16_TemperaturaMandata                 */ { "Temperatura di mandata","Supply air temperature [C°]"},
/* 24 LBL_20_Matricola                          */ { "Matricola PLC","Serial number"},
/* 25 LBL_21_IndirizzoSlave                     */ { "Indirizzo slave","Slave address"},
/* 26 LBL_30_ModalitaOffdaRemoto                */ { "Modalità 'OFF da remoto'","'Remote OFF' mode"},
/* 27 LBL_31_ModalitaEcoDaTermostato            */ { "Modalità economy da termostato","Economy mode from thermostat"},
/* 28 LBL_32_ModalitaEconDaID1                  */ { "Modalità economy da DI1","Economy mode from DI1"},
/* 29 LBL_33_ModalitaEconDaID2                  */ { "Modalità economy da DI2","Economy mode from DI2"},
/* 30 LBL_34_ModalitaEconDaID3                  */ { "Modalità economy da DI3","Economy mode from DI3"},
/* 31 LBL_35_ModalitaEcondaAnal                 */ { "Modalità economy da analogico 2","Economy mode from AI2"},
/* 32 LBL_36_ModalitaEcondaPLCinRete            */ { "Modalità economy da PLC in rete","Economy mode from netw. PLC"},
/* 33 LBL_37_ModalitaEcondaMODBUS               */ { "Modalità economy da MODBUS","Economy mode from BMS"},
/* 34 LBL_38_OffResistPrimaSoglia               */ { "OFF Res. da T. interna 1° soglia","E. heater OFF from int T. 1st threshold"},
/* 35 LBL_39_LimiteMassimoTMandata              */ { "Limita massimo T. mandata","Supply air maximum temperature limit"},
/* 36 LBL_3A_RiduzuineDCMaxResPerPort           */ { "Riduzione DC max res.\nper portata","Max DC reduction due to flow r."},
/* 37 LBL_40_SondaTempInterna                   */ { "Sonda temperatura interna","Internal temperature probe"},
/* 38 LBL_41_SondaTempMandata                   */ { "Sonda temperatura mandata","Supply air temperature"},
/* 39 LBL_42_SondaTempAmbiente                  */ { "Sonda temperatura ambiente","Room temperature"},
/* 40 LBL_43_AltaTemIntSecondaSoglia            */ { "Alta temperatura interna 2° soglia","High internale temp. 2nd threshold"},
/* 41 LBL_44_InterventoTermResistenza           */ { "Intervento termostato resistenza","El. heather thermpstat tripped"},
/* 42 LBL_45_TermStanzaNonCollegato             */ { "Termostato stanza non collegato","Room thermostat not connected"},
/* 43 LBL_46_SondaTemStanza                     */ { "Sonda termostato stanza","Room thermostat probe"},
/* 44 LBL_47_CircResistenzaAperta               */ { "Circuito resistenza aperto","El. heather open circuit"},
/* 45 LBL_48_CircInnescoRes                     */ { "Circuito innesco resistenza","El. heather trigger circuit"},
/* 46 LBL_49_Serranda                           */ { "Serranda","Dumper"},
/* 47 LBL_4A_SensorePressione                   */ { "Sensore di pressione","Pressure sensor"},
/* 48 LBL_4B_PortataBassa                       */ { "Portata bassa","Low flow rate"},
/* 49 LBL_50_TemperaturaScheda                  */ { "Temperatura scheda PLC [C°]","Board temperature [C°]"},
/* 50 LBL_51_FrequenzaRete                      */ { "Frequenza di rete [Hz]","Mains frequency [Hz]"},
/* 51 LBL_52_24Volt                             */ { "Tensione alimentazione [V]","Power supply [V]"},
/* 52 LBL_53_RiduzioneTemperatura               */ { "Riduzione riscaldamento temp. scheda.[%]","Heating reduction board temp.[%]"},
/* 53 LBL_60_ApertutaSerranda                   */ { "Apertura serranda [%]","Damper opening [%]"},
/* 54 LBL_61_ComadoResistenza                   */ { "Comando resistenza [%]","El. heather control [%]"},
/* 55 LBL_62_RichMaxRaffreddamento              */ { "Richiesta max. raffreddamento","Max cooling request"},
/* 56 LBL_09_TensioneSerranda                   */ { "Tensione serranda [V]","Damper voltage [V]"},
/* 57 LBL_63_MasterSlave                        */ { "Master/Slave","Master/Slave"},
/* 58 LBL_54_TensioneRete                       */ { "Sovratensione","Overvoltage"},
/* 59 LBL_55_RS485_O_ERR                        */ { "Errore comunicazione PLC","Communication error PLC"},
/* 60 LBL_56_TEMP_TERMOSTATO                    */ { "Temperatura termostato [C°]","Thermostat temperature [C°]"},
/* 61 LBL_57_ADJTEMPTERM                        */ { "Regolazione del setpoint di temperatura ","Adjustment of temperature setpoint"},
/* 62 LBL_58_PRIMARYDEVICE                      */ { "Dispositivo primario","Primary device"},

// ----------------------------------------------------------------------------------------------------------
/* 63 FS_GB_0_FANCOIL                      */ { "Fancoil","Fancoil"},
/* 64 FS_LBL_0_00                          */ { "Matricola","Serial number"},
/* 65 FS_LBL_0_01                          */ { "Indirizzo","Save address"},
/* 66 FS_LBL_0_02                          */ { "Tipologia dispositivo","Device type"},
/* 67 FS_LBL_0_03                          */ { "Tipo FANCOIL","FANCOIL type"},
/* 68 FS_GB_1_INGRESSI                     */ { "Ingressi","Inputs"},
/* 69 FS_LBL_1_00                          */ { "Sonda di regolazione","Regulation probe"},
/* 70 FS_LBL_1_01                          */ { "Setpoint temperatura [C°]","Temperature setpoint [C°]"},
/* 71 FS_LBL_1_02                          */ { "Temperatura interna [C°]","Internal temperature [C°]"},
/* 72 FS_LBL_1_03                          */ { "Pressione differenziale filtro [Pa]","Filter differential pressure [ppm]"},
/* 73 FS_LBL_1_04                          */ { "CO₂ [ppm]","CO₂ [ppm]"},
/* 74 FS_LBL_1_05                          */ { "VOC  [%]","VOC  [%]"},
/* 75 FS_LBL_1_06                          */ { "Temperatura termostato stanza [C°]","Room thermostat temperatura [C°]"},
/* 76 FS_GB_2_REGOLAZIONE                  */ { "Regolazione","Regulations"},
/* 77 FS_LBL_2_00                          */ { "Ventilatore","Fan"},
/* 78 FS_LBL_2_01                          */ { "Velocità ventilatore [rpm]","Fan speed [rpm]"},
/* 79 FS_LBL_2_02                          */ { "Valvola fredda PWM [D.C. %]","Cold PWM valve [D.C. %]"},
/* 80 FS_LBL_2_02Sub                       */ { "DC massimo istantaneo [%]","Maximum instantaneous D.C. [%]"},
/* 81 FS_LBL_2_03                          */ { "Valvola fredda modulante [%]","Cold modulating valve  [%]"},
/* 82 FS_LBL_2_03Sub                       */ { "Modulazione massima [%]","Maximum modulation [%]"},
/* 83 FS_LBL_2_04                          */ { "Resistenza elettrica [%]","El. heater [%]"},
/* 84 FS_LBL_2_04Sub                       */ { "DC massimo istantaneo [%]","Maximum instantaneous D.C. [%]"},
/* 85 FS_LBL_2_05                          */ { "Valvola calda PWM [D.C. %]","PWM heating valve [D.C. %]"},
/* 86 FS_LBL_2_05Sub                       */ { "DC massimo istantaneo [%]","Maximum instantaneous D.C. [%]"},
/* 87 FS_LBL_2_06                          */ { "Valvola calda modulante [%]","Modulating heating valve  [%]"},
/* 88 FS_LBL_2_06Sub                       */ { "Modulazione massima [%]","Maximum modulation [%]"},
/* 89 FS_LBL_2_07                          */ { "Valvola changeover","Changeover valve"},
/* 90 FS_LBL_2_08                          */ { "Riduzione raffreddamento [%]","Cooling reduction [%]"},
/* 91 FS_LBL_2_09                          */ { "Riduzione riscaldamento [%]","Heating reduction [%]"},
/* 92 FS_LBL_2_10                          */ { "Serranda","Damper"},
/* 93 FS_GB_3_STATI                        */ { "Stati","States"},
/* 94 FS_LBL_3_00                          */ { "Fancoil spento da BMS","Fancoil turned OFF from room BMS"},
/* 95 FS_LBL_3_01                          */ { "Fancoil spento da termostato","Fancoil turned OFF from room thermostato"},
/* 96 FS_LBL_3_02                          */ { "Fancoil spento da ingresso DI1","Fancoil OFF from DI1 input"},
/* 97 FS_LBL_3_03                          */ { "Fancoil spento da economy mode","Fancoil OFF from economy mode"},
/* 98 FS_LBL_3_04                          */ { "Modalità economy da DI1 (contatto presenza)","Economy mode from DI1 (Presence Contact)"},
/* 99 FS_LBL_3_05                          */ { "Modalità economy da DI2 (porta terrazza)","Economy mode from DI2 (Balcony door contact)"},
/* 100 FS_LBL_3_06                         */ { "Modalità economy da DI3 (tessera magnetica)","Economy mode from DI3 (Keycard holder)"},
/* 101 FS_LBL_3_07                         */ { "Tipo economy","Economy type"},
/* 102 FS_LBL_3_08                         */ { "Modalità economy da ingressi PLC in rete","Economy mode from in network PLC digital inputs"},
/* 103 FS_LBL_3_09                         */ { "Modalità economy da BMS ‘Energy saving’","Economy mode from BMS"},
/* 104 FS_LBL_3_10                         */ { "Limite di temperatura di mandata risc./Raff.","Heating/cooling supply temperature limit"},
/* 105 FS_LBL_3_11                         */ { "Limitazione riscaldamento da alta temperatura scheda","Heating limitation from high. Temperature board"},
/* 106 FS_LBL_3_12                         */ { "Raffreddamento rapido","Quick cooling"},
/* 107 FS_LBL_3_13                         */ { "Contatore segnalazione filtro sporco [giorni]","Dirty filter warning counter [days]"},
/* 108 FS_LBL_3_14                         */ { "On/Off","On/Off"},
/* 109 FS_GB_4_ALLARMI                         */ { "Allarmi","Alarms"},
/* 110 FS_LBL_4_00                         */ { "Sonda di regolazione","Regulation probe"},
/* 111 FS_LBL_4_01                         */ { "Sonda temperature ripresa","Return air temperature probe"},
/* 112 FS_LBL_4_02                         */ { "Sonda temperature mandata","Supply air temperature probe"},
/* 113 FS_LBL_4_03                         */ { "Allarme temperatura di sicurezza","Safety temperature alarm"},
/* 114 FS_LBL_4_04                         */ { "Intervento termostato di sicurezza","El. heater temperature alarm"},
/* 115 FS_LBL_4_05                         */ { "Temperatura mandata (caldo)","Supply Temperature (heat)"},
/* 116 FS_LBL_4_06                         */ { "Temperatura mandata (freddo)","Room thermostat not connected"},
/* 117 FS_LBL_4_07                         */ { "Termostato stanza non collegato","Room thermostat probe"},
/* 118 FS_LBL_4_08                         */ { "Sonda termostato stanza","El. heater open circuit"},
/* 119 FS_LBL_4_09                         */ { "Circuito resistenza elettrica aperto","El heater trigger circuit"},
/* 120 FS_LBL_4_10                         */ { "Circuito innesco resistenza","General alarm (dry contact output)"},
/* 121 FS_LBL_4_11                         */ { "Allarme generale fancoil (dry contact output)","Fire / external general alarm"},
/* 122 FS_LBL_4_12                         */ { "Allarme incendio/generale esterno","Cumulative fancoil master/slave alarm"},
/* 123 FS_LBL_4_13                         */ { "Allarme cumulativo fancoil master/slave","Fan alarm"},
/* 124 FS_LBL_4_14                         */ { "Allarme ventilatore","Damper alarm"},
/* 125 FS_LBL_4_15                         */ { "Allarme serranda","Pressure sensor alarm"},
/* 126 FS_LBL_4_16                         */ { "Allarme sensore di pressione","Low pressura alarm"},
/* 127 FS_LBL_4_17                         */ { "Allarme bassa pressione","Hi pressure alarm"},
/* 128 FS_LBL_4_18                         */ { "Allarme alta pressione","0-10V valve actuator alarm"},
/* 129 FS_LBL_4_19                         */ { "Allarme attuatore valvola 0-10 V","Dirty filter warning"},
/* 130 FS_LBL_4_20                         */ { "Segnalazione filtro sporco","Overiddes"},
/* 131 FS_GB_5_FORZATURE                   */ { "Forzature","Overiddes"},
/* 132 FS_LBL_5_00                         */ { "Comando ventilatore [%]","Fan control [%]"},
/* 133 FS_LBL_5_01                         */ { "Comando resistenza [%]","El. heater control [%]"},
/* 134 FS_LBL_5_02                         */ { "Apertura valvola","Valve opening"},
/* 135 FS_LBL_5_03                         */ { "Apertura serranda [%]","Damper opening"},





// --------------------------------------------------------------------------- T1
/* 136 T1_GB_S0                            */ { "Stati","States"},
/* 137 T1_LBL_S0_00                        */ { "Temperatura NTC1 [C°]","NTC1 temperature [C°]"},
/* 138 T1_LBL_S0_01                        */ { "Temperatura NTC2 [C°]","NTC2 temperature [C°]"},
/* 139 T1_LBL_S0_02                        */ { "Temperatura NTC ext. [C°]","Ext.  NTC temperature [C°]"},
/* 140 T1_LBL_S0_03                        */ { "Temperatura NTC scheda [C°]","Temperatura NTC board [C°]"},
/* 141 T1_LBL_S0_04                        */ { "Setpoint","Setpoint"},
/* 142 T1_LBL_S0_05                        */ { "Tensione alimentazione [V] ","Power supplu [V]"},
/* 143 T1_LBL_S0_06                        */ { "Errore sonda","Probe error"},
/* 144 T1_GB_S1                            */ { "Forzature","Overiddes"},
/* 145 T1_GB_S2                            */ { "Stato dispositivo","Device status"},
/* 146 T1_LBL_S2_00                        */ { "Matricola","Serial number"},
/* 147 T1_LBL_S2_01                        */ { "Informazioni dispositivo","Info device"},
/* 148 T1_LBL_S2_02                        */ { "Indirizzo","Address"},




// ---------------------------------------------------------------------------- T2
// T2
/* 149 T2_LBL_S0_00                        */ { "Velocità ventola","Fan speed"},
/* 150 T2_LBL_S0_01                        */ { "Ventola manuale/automatico","Amanual/automaitc fan"},
/* 151 T2_LBL_S0_02                        */ { "LED MKR","LED MKR"},
/* 152 T2_LBL_S0_03                        */ { "LED DND","LED DND"},
/* 153 T2_LBL_S0_04                        */ { "Sovracorrente MKR","Overcurrent MKR"},
/* 154 T2_LBL_S0_05                        */ { "Sovracorrente DND","Overcurrent DND"},
/* 155 T2_LBL_G2_00                        */ { "Temperatura","Temperature"},
/* 156 T2_LBL_S2_00                        */ { "Setpoint default [C°]","Default temperature setpoint [C°]"},
/* 157 T2_LBL_S2_01                        */ { "Deviazione max setpoint default [C°]","Max. default setpoint deviation [C°]"},







        };

        static public string getStr(Indice ind)
        {
            return localizzazioni[(int)ind, loca.getLingua()];
        }
    }
}



